#!/usr/bin/env bash
# Regenerate syntax/zshrs.vim from the zshrs binary's own reflection tables.
# Run after a zshrs upgrade so the highlighter never drifts from the shell.
#
#   ./scripts/gen_syntax.sh        # uses `zshrs` on $PATH
#   ZSHRS=/path/to/zshrs ./scripts/gen_syntax.sh
#
# Sources of truth (the binary, not a hand-maintained list):
#   builtins      : zshrs --dump-reflection | jq -r '.builtins|keys[]'
#   extensions    : zshrs --dump-reflection | jq -r '.extensions|keys[]'
#   special vars  : zshrs --dump-reflection | jq -r '.special_vars|keys[]'
#
# The 24 control + 10 declaration keywords are part of the shell grammar
# (not dumped as builtins), so they are hardcoded below.
#
# Partitioning rules so each face is distinct:
#   * builtins   = .builtins, restricted to identifier names, MINUS the
#                  extension names and MINUS the keyword names (so the
#                  zshrs extensions get their own highlight group).
#   * extensions = .extensions, restricted to identifier names (the
#                  zshrs-specific additions — their own face).
#   * specialvars= .special_vars, restricted to identifier names.
set -euo pipefail

zshrs="${ZSHRS:-zshrs}"
here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/syntax/zshrs.vim"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

ident='^[A-Za-z_][A-Za-z0-9_]*$'

# --- static keyword tables (the shell grammar; not in --dump-reflection) ----
cat > "$tmp/kw_control.txt" <<'KW'
always
break
case
continue
do
done
elif
else
end
esac
exit
fi
for
foreach
function
if
in
logout
repeat
return
select
then
until
while
KW
cat > "$tmp/kw_decl.txt" <<'KW'
declare
export
float
integer
let
local
readonly
set
shift
typeset
KW
sort -u "$tmp/kw_control.txt" "$tmp/kw_decl.txt" > "$tmp/kw_all.txt"

# --- pull the reflection tables ---------------------------------------------
"$zshrs" --dump-reflection | jq -r '.extensions|keys[]'   | grep -E "$ident" | sort -u > "$tmp/ext.txt"
"$zshrs" --dump-reflection | jq -r '.special_vars|keys[]' | grep -E "$ident" | sort -u > "$tmp/svar.txt"
"$zshrs" --dump-reflection | jq -r '.builtins|keys[]'     | grep -E "$ident" | sort -u > "$tmp/b_all.txt"

# builtins minus extensions minus keywords -> their own face
comm -23 "$tmp/b_all.txt" "$tmp/ext.txt"      > "$tmp/b_noext.txt"
comm -23 "$tmp/b_noext.txt" "$tmp/kw_all.txt" > "$tmp/builtins.txt"

nb="$(wc -l < "$tmp/builtins.txt"  | tr -d ' ')"
ne="$(wc -l < "$tmp/ext.txt"       | tr -d ' ')"
nv="$(wc -l < "$tmp/svar.txt"      | tr -d ' ')"
nc="$(wc -l < "$tmp/kw_control.txt"| tr -d ' ')"
nd="$(wc -l < "$tmp/kw_decl.txt"   | tr -d ' ')"
ver="$("$zshrs" --version 2>/dev/null | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -1)"

# `:syntax keyword` rejects names that collide with its own argument keywords
# (E395), e.g. the extension literally named `fold`. Pull those out and emit
# them with `:syntax match \<word\>` instead.
printf '%s\n' contained containedin nextgroup transparent skipwhite skipnl \
  skipempty contains oneline fold display extend conceal cchar concealends \
  keepend excludenl | sort -u > "$tmp/reserved.txt"

split_reserved() {  # <infile> <safe-out> <reserved-out>
  comm -23 "$1" "$tmp/reserved.txt" > "$2"
  comm -12 "$1" "$tmp/reserved.txt" > "$3"
}
split_reserved "$tmp/builtins.txt" "$tmp/b_safe.txt"  "$tmp/b_resv.txt"
split_reserved "$tmp/ext.txt"      "$tmp/e_safe.txt"  "$tmp/e_resv.txt"
split_reserved "$tmp/svar.txt"     "$tmp/v_safe.txt"  "$tmp/v_resv.txt"

wrap() { awk -v g="$1" 'BEGIN{n=0}
  {if(n==0)printf "syntax keyword %s",g; printf " %s",$0; n++; if(n==15){print "";n=0}}
  END{if(n>0)print ""}'; }
matchwords() { awk -v g="$1" '{printf "syntax match %s \"\\<%s\\>\"\n",g,$0}'; }

{
cat <<HEAD
" vim-zsh — syntax highlighting for zshrs (the Rust zsh rewrite)
"
" GENERATED by scripts/gen_syntax.sh from the zshrs binary's reflection tables
" (\`zshrs --dump-reflection\`): builtins, extensions, special_vars. A standalone
" zshrs grammar — NOT a reskin of Vim's builtin zsh / perl syntax. Filetype is
" \`zshrs\` (not \`zsh\`) so it never clobbers Vim's bundled zsh highlighter.
" Regenerate after a zshrs upgrade; do not edit by hand.
"
" Generated against zshrs ${ver:-unknown} — ${nb} builtins, ${ne} extensions,
" ${nv} special vars, ${nc} control + ${nd} declaration keywords.

if exists('b:current_syntax')
  finish
endif

syntax case match
syntax sync minlines=50

" ---------------------------------------------------------------------------
" Comments / shebang
" ---------------------------------------------------------------------------
syntax keyword zshrsTodo contained TODO FIXME XXX NOTE HACK
syntax match   zshrsComment "#.*\$" contains=zshrsTodo,@Spell
syntax match   zshrsShebang "\%^#!.*\$"

" ---------------------------------------------------------------------------
" Numbers
" ---------------------------------------------------------------------------
syntax match zshrsNumber "\<\d\+\>"
syntax match zshrsNumber "\<0x\x\+\>"
syntax match zshrsNumber "\<0b[01]\+\>"
syntax match zshrsFloat  "\<\d\+\.\d\+\%([eE][-+]\?\d\+\)\?\>"

" ---------------------------------------------------------------------------
" Variables (sigils)
" ---------------------------------------------------------------------------
" Positional / punctuation specials: \$1 \$# \$@ \$? \$! \$\$ \$* \$- \$0
syntax match zshrsSpecialVar "\$[#@?!*\$0-9-]"
syntax match zshrsSpecialVar "\$\d\+"
" \${...} parameter expansion (with nested interpolation)
syntax region zshrsParamExp matchgroup=zshrsSigil start="\${" end="}" contains=zshrsSpecialVar,zshrsParamExp
" \$name scalar reference
syntax match zshrsScalar "\$\h\w*"

" ---------------------------------------------------------------------------
" Command substitution
" ---------------------------------------------------------------------------
syntax region zshrsCmdSub matchgroup=zshrsSigil start="\$(" end=")" contains=TOP
syntax region zshrsBacktick start=+\`+ skip=+\\\\\`+ end=+\`+ contains=zshrsScalar,zshrsParamExp,zshrsStringEscape

" ---------------------------------------------------------------------------
" Strings
" ---------------------------------------------------------------------------
syntax match  zshrsStringEscape contained "\\\\."
syntax region zshrsStringS start=+'+ skip=+\\\\'+ end=+'+
syntax region zshrsStringD start=+"+ skip=+\\\\"+ end=+"+ contains=zshrsStringEscape,zshrsScalar,zshrsParamExp,zshrsCmdSub,zshrsSpecialVar,@Spell

" ---------------------------------------------------------------------------
" Here-docs  <<EOF  <<-EOF  <<'EOF'
" ---------------------------------------------------------------------------
syntax region zshrsHereDoc matchgroup=zshrsStringD start=+<<-\?"\=\z(\h\w*\)"\=+ end=+^\s*\z1\$+ contains=zshrsScalar,zshrsParamExp,zshrsCmdSub,zshrsStringEscape
syntax region zshrsHereDoc matchgroup=zshrsStringS start=+<<-\?'\z(\h\w*\)'+ end=+^\s*\z1\$+

" ---------------------------------------------------------------------------
" Keywords (shell grammar — control flow + declarations)
" ---------------------------------------------------------------------------
HEAD

wrap zshrsControl < "$tmp/kw_control.txt"
wrap zshrsDecl    < "$tmp/kw_decl.txt"

cat <<'MID'

" ---------------------------------------------------------------------------
" Builtins (zshrs --dump-reflection .builtins, minus extensions + keywords)
" ---------------------------------------------------------------------------
MID

wrap zshrsBuiltin < "$tmp/b_safe.txt"
matchwords zshrsBuiltin < "$tmp/b_resv.txt"

cat <<'MID'

" ---------------------------------------------------------------------------
" Extensions (zshrs-specific builtins — the world-first additions)
" ---------------------------------------------------------------------------
MID

wrap zshrsExtension < "$tmp/e_safe.txt"
matchwords zshrsExtension < "$tmp/e_resv.txt"

cat <<'MID'

" ---------------------------------------------------------------------------
" Named special variables (bare-word forms, e.g. PATH, ZSH_VERSION, RANDOM)
" ---------------------------------------------------------------------------
MID

wrap zshrsSpecialVar < "$tmp/v_safe.txt"
matchwords zshrsSpecialVar < "$tmp/v_resv.txt"

cat <<'TAIL'

" ---------------------------------------------------------------------------
" Highlight links
" ---------------------------------------------------------------------------
highlight default link zshrsComment      Comment
highlight default link zshrsShebang      PreProc
highlight default link zshrsTodo         Todo
highlight default link zshrsNumber       Number
highlight default link zshrsFloat        Float
highlight default link zshrsSigil        Identifier
highlight default link zshrsScalar       Identifier
highlight default link zshrsParamExp     Identifier
highlight default link zshrsSpecialVar   Identifier
highlight default link zshrsCmdSub       Special
highlight default link zshrsBacktick     String
highlight default link zshrsStringS      String
highlight default link zshrsStringD      String
highlight default link zshrsHereDoc      String
highlight default link zshrsStringEscape SpecialChar
highlight default link zshrsControl      Statement
highlight default link zshrsDecl         StorageClass
highlight default link zshrsBuiltin      Function
highlight default link zshrsExtension    PreProc

let b:current_syntax = 'zshrs'
TAIL
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines): $nb builtins, $ne extensions, $nv special vars, $nc+$nd keywords, zshrs ${ver:-unknown}"
